export {default as About} from './About'
export { default as ContactUs } from './ContactUs'
export { default as Home } from './Home'
export { default as Services } from './Services'
export { default as Login } from './Login'
export { default as SignUp } from './SignUp'
